const currentDate = new Date().toISOString().split("T")[0];
export const satellites = {
  "Landsat 8 Real-Time": {
    satellite: "LANDSAT/LC08/C02/T1_RT_TOA",
    bands: {
      blue: "B2",
      green: "B3",
      red: "B4",
      nir: "B5",
      swir1: "B6",
      swir2: "B7",
    },
    scale: 30,
    min: 0.03,
    max: 0.2,
    startDate: "2013-03-18",
    endDate: currentDate,
  },
  "Sentinel 2 TOA": {
    satellite: "COPERNICUS/S2_HARMONIZED",
    scale: 10,
    bands: {
      blue: "B2",
      green: "B3",
      red: "B4",
      nir: "B8",
      "red edge 4": "B8A",
      cirrus: "B10",
      swir1: "B11",
      swir2: "B12",
      ndvi: "NDVI",
    },
    min: 300,
    max: 1500,
    startDate: "2015-06-23",
    endDate: currentDate,
  },
  "Sentinel 2 SR": {
    satellite: "COPERNICUS/S2_SR_HARMONIZED",
    scale: 10,
    bands: {
      blue: "B2",
      green: "B3",
      red: "B4",
      nir: "B8",
      "red edge 4": "B8A",
      cirrus: "B10",
      swir1: "B11",
      swir2: "B12",
      ndvi: "NDVI",
    },
    min: 300,
    max: 1500,
    startDate: "2017-03-28",
    endDate: currentDate,
  },
  "Sentinel 3": {
    satellite: "COPERNICUS/S3/OLCI",
    bands: {
      blue: "Oa04_radiance",
      green: "Oa06_radiance",
      red: "Oa08_radiance",
      nir: "Oa17_radiance",
    },
    min: 15,
    max: 70,
    startDate: "2016-10-18",
    endDate: currentDate,
  },
  // The combined objects below have this weirdish looking thing for the "bands" key but it's
  // done this way so we don't have to rewrite everything else. Essentially the "sat0Bands" and "sat1Bands"
  // objects help the combiner resolve what band is associated with what and then the "bands"
  // object exists so other functions that look up key.bands don't have to be rewritten just for combined
  // satellites. e.g. key.bands.blue returns "blue" instead of "B1" and the visualizer resolves it just fine
  "L5/L8 TOA Combined": {
    combined: true,
    keys: ["Landsat 5 TOA", "Landsat 8 TOA"],
    sat0: "LANDSAT/LT05/C02/T1_TOA",
    sat0Bands: {
      blue: "B1",
      green: "B2",
      red: "B3",
      nir: "B4",
      swir1: "B5",
      swir2: "B7",
    },
    sat1: "LANDSAT/LC08/C02/T1_TOA",
    sat1Bands: {
      blue: "B2",
      green: "B3",
      red: "B4",
      nir: "B5",
      swir1: "B6",
      swir2: "B7",
    },
    bands: {
      blue: "blue",
      green: "green",
      red: "red",
      nir: "nir",
      swir1: "swir1",
      swir2: "swir2",
    },
    startDate: "1984-03",
    endDate: currentDate,
    scale: 30,
    min: 0,
    max: 0.4,
  },
  "L5/L8 SR Combined": {
    combined: true,
    keys: ["Landsat 5 SR", "Landsat 8 SR"],
    sat0: "LANDSAT/LT05/C02/T1_L2",
    sat0Bands: {
      blue: "SR_B1",
      green: "SR_B2",
      red: "SR_B3",
      nir: "SR_B4",
      swir1: "SR_B5",
      swir2: "SR_B7",
    },
    sat1: "LANDSAT/LC08/C02/T1_L2",
    sat1Bands: {
      blue: "SR_B2",
      green: "SR_B3",
      red: "SR_B4",
      nir: "SR_B5",
      swir1: "SR_B6",
      swir2: "SR_B7",
    },
    bands: {
      blue: "blue",
      green: "green",
      red: "red",
      nir: "nir",
      swir1: "swir1",
      swir2: "swir2",
    },
    startDate: "1984-03",
    endDate: currentDate,
    scale: 30,
    min: 5000,
    max: 15000,
  },
  "L8/L9 TOA Combined": {
    combined: true,
    keys: ["Landsat 8 TOA", "Landsat 9 TOA"],
    sat0: "LANDSAT/LC08/C02/T1_TOA",
    sat0Bands: {
      blue: "B2",
      green: "B3",
      red: "B4",
      nir: "B5",
      swir1: "B6",
      swir2: "B7",
    },
    sat1: "LANDSAT/LC09/C02/T1_TOA",
    sat1Bands: {
      blue: "B2",
      green: "B3",
      red: "B4",
      nir: "B5",
      swir1: "B6",
      swir2: "B7",
    },
    bands: {
      blue: "blue",
      green: "green",
      red: "red",
      nir: "nir",
      swir1: "swir1",
      swir2: "swir2",
    },
    startDate: "2013",
    endDate: currentDate,
    scale: 30,
    min: 0,
    max: 0.4,
  },
  "L8/L9 SR Combined": {
    combined: true,
    sat0: "LANDSAT/LC08/C02/T1_L2",
    sat0Bands: {
      blue: "SR_B2",
      green: "SR_B3",
      red: "SR_B4",
      nir: "SR_B5",
      swir1: "SR_B6",
      swir2: "SR_B7",
    },
    sat1: "LANDSAT/LC09/C02/T1_L2",
    sat1Bands: {
      blue: "SR_B2",
      green: "SR_B3",
      red: "SR_B4",
      nir: "SR_B5",
      swir1: "SR_B6",
      swir2: "SR_B7",
    },
    bands: {
      blue: "blue",
      green: "green",
      red: "red",
      nir: "nir",
      swir1: "swir1",
      swir2: "swir2",
    },
    startDate: "2013",
    endDate: currentDate,
    scale: 30,
    min: 5000,
    max: 15000,
  },
};
